name: schedule_test_dbt_run

on:
schedule:
    # run at 7AM every single day
    # https://crontab.guru <-- for generating CRON expression
    - cron: "0 7 * * *"
push:
    branches:
    # run on push to development branch
    - development
env:
DBT_PROFILES_DIR: ./

DBT_SNOWFLAKE_USERNAME: ${{ secrets.DBT_SNOWFLAKE_USERNAME }}
DBT_SNOWFLAKE_PW: ${{ secrets.DBT_SNOWFLAKE_PW }}


jobs:
schedule_dbt_run:
    name: schedule_dbt_run
    runs-on: ubuntu-latest

    steps:
    - name: Check out
        uses: actions/checkout@master

    - uses: actions/setup-python@v1
        with:
        python-version: "3.7.x"

    - name: Install dependencies
        run: |
        pip install dbt
        dbt deps

    # dbt related commands here - run use --target prod/dev to run for specific environments
    - name: Run dbt models
        run: dbt run

    