name: schedule_test_dbt_run

on:
  schedule:
    # Ejecutar a las 1:20 AM todos los días
    # https://crontab.guru <-- para generar la expresión CRON
    - cron: "20 11 * * *"
  push:
    branches:
      # Ejecutar en cada empuje a la rama master
      - master
  workflow_dispatch:
env:
  DBT_PROFILES_DIR: ./
  DBT_USER: ${{ secrets.DBT_SNOWFLAKE_USERNAME }}
  DBT_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PW }}

jobs:
  schedule_dbt_run:
    name: schedule_dbt_run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install dbt-snowflake
        cd dbt_git_act
        dbt deps

    # Comandos relacionados con dbt aquí - usa --target prod/dev para ejecutar en entornos específicos
    - name: Run dbt models
      run: |
        cd dbt_git_act
        dbt run
