name: schedule_test_dbt_run

on:
  schedule:
    # Ejecutar a las 1:20 AM todos los días
    # https://crontab.guru <-- para generar la expresión CRON
    - cron: "20 11 * * *"
  push:
    branches:
      # Ejecutar en cada empuje a la rama master
      - slack-notification
  workflow_dispatch:
  check_run:
    types: [rerequested, completed]
env:
  DBT_PROFILES_DIR: ./
  DBT_USER: ${{ secrets.DBT_SNOWFLAKE_USERNAME }}
  DBT_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PW }}

jobs:
  schedule_dbt_run:
    name: schedule_dbt_run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install dbt-snowflake
        cd dbt_git_act
        dbt deps

    # Comandos relacionados con dbt aquí - usa --target prod/dev para ejecutar en entornos específicos
    - name: Run dbt models
      run: |
        cd dbt_git_act
        dbt run
    - name: Notify by Email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "GitHub Actions Notification"
        body: "Your GitHub Actions workflow has completed."
        from: "victor.hernandez@clouddataconsulting.com"
        to: "victor.hernandez@clouddataconsulting.com"
        start_tls: true
    - name: Notify on Failure
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "GitHub Actions Notification - Failure"
        body: "Your GitHub Actions workflow has failed. for more details check your workflow."
        from: "victor.hernandez@clouddataconsulting.com"
        to: "victor.hernandez@clouddataconsulting.com"
        start_tls: true
    