name: schedule_test_dbt_run

on:
  schedule:
    # Ejecutar a las 1:20 AM todos los días
    # https://crontab.guru <-- para generar la expresión CRON
    - cron: "20 11 * * *"
  push:
    branches:
      # Ejecutar en cada empuje a la rama master
      - master
  workflow_dispatch:
  
env:
  DBT_PROFILES_DIR: ./
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

jobs:
  schedule_dbt_run:
    name: schedule_dbt_run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Add Tailscale repository and install Tailscale
      run: |
       curl -fsSL https://tailscale.com/install.sh | sh

    - name: Authenticate Tailscale
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --exit-node=52.33.61.139

    - name: Install dependencies
      run: |
        pip install dbt-snowflake
        cd dbt_git_act
        dbt deps

    - name: Run dbt models
      run: |
        cd dbt_git_act
        dbt run
